source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/xiaobt/FFSpecs.git'

use_frameworks!

target 'FFAPIsKit_Example' do
  pod 'FFAPIsKit', :path => '../'

  target 'FFAPIsKit_Tests' do
    inherit! :search_paths

    
  end
end
